### ISSUE TITLE
Support 360-day-method

### ISSUE THREAD

**Issue by Gravitar64** [arrow-py/arrow#914]
Actual it is possible to calculate the time-difference between 2 arrow.dates b.e. diff = dat1 - dat2. The result (diff) is an arrow-time-diff-object. With diff.days we can get the difference in days. 

Actual it is not possible to calculate the difference in days with the 360-day-method. Where every month is calculated by 30 days. It would be very helpfull (i.E. for calculating interest values) to get the day-diff with this method.

Detailed description here: https://en.wikipedia.org/wiki/Day_count_convention#30/360_US

Thx for you're work with arrow, I use this module every time time-calculations necessary.

**Comment by systemcatch** [comment]
Hey @Gravitar64 I'm glad you find arrow useful.

As I understand it you want a an `Arrow` subclass with a fixed 30 day months?

**Comment by Gravitar64** [comment]
Yes! It's for interest calculation where every month calculated with 30 days and a year has always 360 days.

**Comment by systemcatch** [comment]
Reading about this convention I don't think we'd put it in arrow directly due to it's specialized nature and potential for causing confusion. However I think this could work well as a custom subclass or more likely an independent package.

I found https://pypi.org/project/bond-pricing/, maybe that helps you?
